const BASE_SEED=__SEED__;
const STORE='bbl-draft-assistant-v4';
const DEFAULT_SLOTS={G:1,F:1,C:1,GFC:2,BENCH:8};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const freshDraft=(name='Draft 1')=>({name,mine:[],taken:[],history:[],maxActive:5,draftSlot:BASE_SEED.settings.slot,weights:[...BASE_SEED.settings.weights],slots:{...DEFAULT_SLOTS},compare:[],theme:'dark',created:new Date().toISOString()});
let db={activeId:'draft-1',drafts:{'draft-1':freshDraft()},customPlayers:null};
try{const saved=JSON.parse(localStorage.getItem(STORE));if(saved?.drafts)db=saved}catch(e){}
let state=db.drafts[db.activeId]||freshDraft();
Object.values(db.drafts).forEach(d=>{d.maxActive=5;d.draftSlot=Math.max(1,Math.min(BASE_SEED.settings.teams,Number(d.draftSlot)||BASE_SEED.settings.slot));d.slots={...DEFAULT_SLOTS}});
let players=db.customPlayers||BASE_SEED.players;
let visiblePlayers=[];
const save=()=>{db.drafts[db.activeId]=state;db.customPlayers=db.customPlayers;localStorage.setItem(STORE,JSON.stringify(db))};
const toast=msg=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)};
const download=(name,text,type='application/json')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
const drafted=()=>players.filter(p=>state.mine.includes(p.name));
const selectedNames=()=>new Set([...state.mine,...state.taken]);
function pickOrder(pick){const n=BASE_SEED.settings.teams,round=Math.ceil(pick/n),within=(pick-1)%n+1;let reverse=round===2||round===3||(round>=5&&round%2===1);return {round,slot:reverse?n-within+1:within}}
function nextMyPick(){for(let p=state.history.length+1;p<=BASE_SEED.settings.teams*BASE_SEED.settings.rounds;p++)if(pickOrder(p).slot===state.draftSlot)return p;return '—'}
function positionGroup(pos){return pos==='PG'||pos==='SG'?'G':pos==='SF'||pos==='PF'?'F':'C'}
function activeLineup(playersToday){const counts={G:0,F:0,C:0};playersToday.forEach(p=>counts[positionGroup(p.pos)]++);const dedicated=Math.min(1,counts.G)+Math.min(1,counts.F)+Math.min(1,counts.C),remaining=playersToday.length-dedicated;return Math.min(5,dedicated+Math.min(2,remaining))}
function scheduleLoads(roster=drafted()){return BASE_SEED.dates.map((_,i)=>activeLineup(roster.filter(p=>BASE_SEED.schedules[p.team]?.[i])))}
function positionNeed(p){const group=positionGroup(p.pos),counts={G:0,F:0,C:0};drafted().forEach(x=>counts[positionGroup(x.pos)]++);const minimum={G:1,F:1,C:1}[group],balanced={G:4,F:4,C:3}[group],count=counts[group];if(count<minimum)return 100;return Math.max(35,Math.min(92,76+(balanced-count)*10))}
function scarcity(p){const available=players.filter(x=>!selectedNames().has(x.name)&&x.pos===p.pos&&x.adp<=(state.history.length+35)).length;return Math.max(0,Math.min(10,(8-available)*1.5))}
function fitScore(p){if(!state.mine.length)return 70;const roster=drafted(),before=scheduleLoads(roster),after=scheduleLoads([...roster,p]),games=BASE_SEED.schedules[p.team]||[];let useful=0,total=0;games.forEach((g,i)=>{if(!g)return;total++;if(after[i]>before[i])useful+=BASE_SEED.nbaGames[i]<=5?1.12:BASE_SEED.nbaGames[i]<=7?1.06:1});const schedule=total?Math.min(100,useful/total*100):35;return Math.round(schedule*.85+positionNeed(p)*.15)}
function availabilityAtNextPick(p){const target=Number(nextMyPick());if(!Number.isFinite(target))return 0;const spread=p.estimated?13:9;return 1/(1+Math.exp((target-p.adp)/spread))}
function availabilityAtPick(p,target){const spread=p.estimated?13:9;return 1/(1+Math.exp((target-p.adp)/spread))}
function explanation(p){const parts=[];const now=state.history.length+1;if(p.adp<now-5)parts.push(`${Math.round(now-p.adp)} picks past CBS ADP`);parts.push(`${p.bblPpg.toFixed(1)} projected BBL points/game${p.projectionEstimated?' (estimated)':''}`);if(p.fit>=82)parts.push('adds usable games on open roster dates');if(positionNeed(p)>=80)parts.push(`fills a ${p.pos} need`);if(p.playoff>=85)parts.push('elite P22–P24 schedule');return parts.slice(0,3).join(' · ')}
function scoredPlayers(){const sum=state.weights.reduce((a,b)=>a+b,0)||1;return players.map(p=>{const fit=fitScore(p),overall=(p.value*state.weights[0]+p.playoff*state.weights[1]+fit*state.weights[2])/sum,availability=availabilityAtNextPick(p);const call=availability<.35?'TAKE NOW':availability>.72?'WAIT':'GOOD VALUE';const item={...p,fit,overall,call,availability};item.why=explanation(item);return item}).filter(p=>!selectedNames().has(p.name)).sort((a,b)=>b.overall-a.overall||a.adp-b.adp)}
function projectedDraftPath(limit=3){let pool=scoredPlayers().map(p=>({...p,marketOrder:p.rank*.65+p.adp*.35})),pick=state.history.length+1;const results=[];while(pool.length&&pick<=BASE_SEED.settings.teams*BASE_SEED.settings.rounds&&results.length<limit){const order=pickOrder(pick);pool.sort((a,b)=>a.marketOrder-b.marketOrder||b.overall-a.overall);const choice=pool.shift();if(order.slot===state.draftSlot)results.push({...choice,target:pick,model:'CBS ranking + ADP simulation'});pick++;}return results}
function projectedSelection(){return projectedDraftPath(1)[0]||null}
function targetPickForPlayer(player){const current=state.history.length+1,market=Math.round(player.rank*.65+player.adp*.35),future=[];for(let p=current;p<=BASE_SEED.settings.teams*BASE_SEED.settings.rounds;p++)if(pickOrder(p).slot===state.draftSlot)future.push(p);if(!future.length)return {market,target:'—',urgent:false};const before=future.filter(p=>p<=market);const target=before.length?before[before.length-1]:future[0];return {market,target,urgent:target>market}}
function rebuildLists(){state.mine=state.history.filter(x=>x.owner==='mine').map(x=>x.name);state.taken=state.history.filter(x=>x.owner==='taken').map(x=>x.name)}
function mark(name,owner){if(selectedNames().has(name))return;const pick=state.history.length+1,order=pickOrder(pick);state.history.push({pick,round:order.round,slot:order.slot,name,owner,time:new Date().toISOString()});rebuildLists();save();render();toast(owner==='mine'?'Added to your roster':'Opponent pick recorded')}
function undo(){if(!state.history.length)return toast('Nothing to undo');state.history.pop();rebuildLists();save();render();toast('Last selection undone')}
function removePick(index){state.history.splice(index,1);state.history.forEach((x,i)=>{const o=pickOrder(i+1);x.pick=i+1;x.round=o.round;x.slot=o.slot});rebuildLists();save();render()}
function resetDraft(){if(!confirm('Reset every selection in this draft?'))return;state.history=[];rebuildLists();save();render();toast('Draft reset')}
function filteredPlayers(){let list=scoredPlayers(),q=$('#search').value.trim().toLowerCase(),pos=$('#position').value,team=$('#teamFilter')?.value||'',call=$('#callFilter')?.value||'',sort=$('#sortPlayers')?.value||'rank';if(q)list=list.filter(p=>(p.name+' '+p.team).toLowerCase().includes(q));if(pos)list=list.filter(p=>p.pos===pos);if(team)list=list.filter(p=>p.team===team);if(call)list=list.filter(p=>p.call===call);const dir=sort==='adp'||sort==='rank'?1:-1;list.sort((a,b)=>(a[sort]-b[sort])*dir||a.rank-b.rank);return list}
function renderDraft(){visiblePlayers=filteredPlayers();$('#availableCount').textContent=`${visiblePlayers.length} available`;$('#playerRows').innerHTML=visiblePlayers.map((p,i)=>{const delta=state.history.length+1-p.adp;return `<tr><td><input class="compare-check" type="checkbox" data-compare="${esc(p.name)}" ${state.compare.includes(p.name)?'checked':''}></td><td class="rank">${i+1}</td><td class="player"><strong>${esc(p.name)}</strong><small>${esc(p.team)} · ${esc(p.pos)} · CBS #${p.rank}${p.estimated?' · DEEP POOL':''}</small></td><td class="${delta>5?'fall':delta<-10?'reach':''}">${p.estimated?'~':''}${p.adp.toFixed(1)}</td><td>${p.value.toFixed(1)}</td><td>${p.playoff.toFixed(1)}</td><td>${p.fit}</td><td class="score ${p.overall>=90?'high':''}">${p.overall.toFixed(1)}</td><td><span class="pill ${p.call==='TAKE NOW'?'take':p.call==='WAIT'?'wait':'good'}">${p.call}</span></td><td><div class="actions"><button class="action mine" data-mine="${esc(p.name)}">Mine</button><button class="action taken" data-taken="${esc(p.name)}">Taken</button></div></td></tr>`}).join('');const best=scoredPlayers()[0];if(best){$('#bestName').textContent=best.name;$('#bestMeta').textContent=`${best.team} · ${best.pos} · ${best.overall.toFixed(1)} overall`;$('#bestWhy').textContent=best.why}const projected=projectedSelection();if(projected){$('#projectedName').textContent=projected.name;$('#projectedMeta').textContent=`Projected at your pick #${projected.target} · CBS ADP ${projected.estimated?'~':''}${projected.adp.toFixed(1)}`;$('#projectedWhy').textContent=`${Math.round(projected.availability*100)}% estimated chance to remain available · ${projected.why}`}const pick=state.history.length+1,order=pickOrder(pick);$('#currentPick').textContent=pick>BASE_SEED.settings.teams*BASE_SEED.settings.rounds?'—':pick;$('#nextPick').textContent=nextMyPick();$('#heroCopy').innerHTML=`Round ${order.round} · <span class="slot-name">Slot ${order.slot} ${order.slot===state.draftSlot?'(YOU)':''}</span> · Draft position ${state.draftSlot} · ${state.mine.length}/${BASE_SEED.settings.rounds} roster spots · ${state.taken.length} opponents’ picks`;const mine=drafted();$('#rosterCount').textContent=`${mine.length}/${BASE_SEED.settings.rounds}`;const counts=['G','F','C'].map(group=>({group,n:mine.filter(x=>positionGroup(x.pos)===group).length,need:positionNeed({pos:group==='G'?'PG':group==='F'?'SF':'C'})>=80}));$('#miniRoster').innerHTML=(mine.length?mine.slice(-5).reverse().map(p=>`<div class="side-row"><div><b>${esc(p.name)}</b><br><small>${p.team} · ${p.pos}</small></div><b>${p.value.toFixed(1)}</b></div>`).join(''):'<div class="empty">Use Mine beside a player to start your roster.</div>')+`<div class="position-meter"><span class="position-chip">Daily: 1 G · 1 F · 1 C · 2 GFC</span>${counts.map(x=>`<span class="position-chip ${x.need?'need':''}">${x.group} ${x.n}</span>`).join('')}</div>`;renderAlerts();renderCompareBar()}
function renderAlerts(){const loads=scheduleLoads(),available=scoredPlayers(),gaps=BASE_SEED.dates.map((date,i)=>({date,i,load:loads[i],open:Math.max(0,state.maxActive-loads[i]),games:BASE_SEED.nbaGames[i]})).filter(x=>x.open>0).sort((a,b)=>b.open-a.open||a.games-b.games);$('#miniAlerts').innerHTML=gaps.slice(0,5).map(g=>{const suggested=available.filter(p=>BASE_SEED.schedules[p.team]?.[g.i]).sort((a,b)=>b.overall-a.overall||a.rank-b.rank)[0],draft=suggested?targetPickForPlayer(suggested):null;return `<div class="alert"><div class="${g.open>=3?'critical':'open'}">${g.open>=3?'CRITICAL':'OPEN'}</div><div><div class="date">${new Date(g.date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}</div><div class="slots">${g.games} NBA games</div></div><b>${g.open} slots</b>${suggested?`<div class="coverage-target"><div><span>Suggested coverage</span><b>${esc(suggested.name)}</b><small>${suggested.team} · projected pick #${draft.market} · CBS ADP ${suggested.estimated?'~':''}${suggested.adp.toFixed(1)}</small></div><strong class="${draft.urgent?'urgent-target':''}">${draft.urgent?'TAKE NOW':'TARGET'} #${draft.target}</strong></div>`:''}</div>`}).join('')||'<div class="empty">Every playoff date is fully covered.</div>';$('#gapCount').textContent=gaps.length;$('#unusedSlots').textContent=gaps.reduce((s,g)=>s+g.open,0)}
function renderRoster(){const mine=drafted();$('#rosterTotal').textContent=mine.length;$('#roundsRemaining').textContent=Math.max(0,BASE_SEED.settings.rounds-mine.length);$('#rosterGrid').innerHTML=mine.length?mine.map(p=>`<div class="roster-card"><div><b>${esc(p.name)}</b><br><small>${p.team} · ${p.pos} · ADP ${p.adp.toFixed(1)}</small></div><button class="action" data-remove-name="${esc(p.name)}">Remove</button></div>`).join(''):'<div class="empty">No players drafted yet.</div>'}
function renderCoverage(){const loads=scheduleLoads();let html='<div class="label">Period</div>'+BASE_SEED.dates.map((d,i)=>`<div class="head">P${i<7?22:i<14?23:24} · ${new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}</div>`).join('');html+='<div class="label">My players</div>'+loads.map(n=>`<div class="${n>=state.maxActive?'full':n>=state.maxActive-2?'mid':'low'}">${n}/${state.maxActive}</div>`).join('');html+='<div class="label">NBA games</div>'+BASE_SEED.nbaGames.map(n=>`<div>${n}</div>`).join('');drafted().forEach(p=>{html+=`<div class="label">${esc(p.name.split(' ').slice(-1)[0])} · ${p.team}</div>`+(BASE_SEED.opponents[p.team]||[]).map(opp=>`<div class="${opp?'full':''}">${esc(opp)}</div>`).join('')});$('#heatmap').innerHTML=html}
function renderHistory(){const rows=state.history;$('#historyTotal').textContent=rows.length;$('#currentRound').textContent=pickOrder(rows.length+1).round;$('#historyRows').innerHTML=rows.length?rows.map((h,i)=>{const p=players.find(x=>x.name===h.name)||{};return `<tr><td>${h.pick}</td><td>${h.round}</td><td>Slot ${h.slot}</td><td><b>${esc(h.name)}</b></td><td>${p.team||''}</td><td>${p.pos||''}</td><td class="${h.owner==='mine'?'history-mine':''}">${h.owner==='mine'?'Mine':'Opponent'}</td><td><button class="action danger" data-remove-pick="${i}">Remove</button></td></tr>`}).join(''):'<tr><td colspan="8" class="empty">No selections entered.</td></tr>'}
function renderSettings(){$('#maxActive').value=5;$('#draftPosition').value=state.draftSlot;['Value','Playoff','Fit'].forEach((n,i)=>{$('#weight'+n).value=Math.round(state.weights[i]*100);$('#out'+n).textContent=Math.round(state.weights[i]*100)+'%'});$('#draftSelect').innerHTML=Object.entries(db.drafts).map(([id,d])=>`<option value="${id}" ${id===db.activeId?'selected':''}>${esc(d.name)}</option>`).join('');document.body.classList.toggle('light-mode',state.theme==='light')}
function renderCompareBar(){const n=state.compare.length;$('#compareCount').textContent=`${n} selected`;$('#compareBar').classList.toggle('show',n>0);$('#openCompare').disabled=n<2}
function renderIntel(){const list=scoredPlayers(),path=projectedDraftPath(3);$('#intelPicks').innerHTML=path.length?path.map(p=>`<div class="intel-row"><span>Pick #${p.target}</span><b>${esc(p.name)}</b><small>CBS #${p.rank} · ADP ${p.estimated?'~':''}${p.adp.toFixed(1)}</small></div>`).join(''):'<div class="intel-empty">Your draft is complete.</div>';const remaining100=list.filter(p=>p.rank<=100),positions=['PG','SG','SF','PF','C'];$('#intelScarcity').innerHTML=positions.map(pos=>{const n=remaining100.filter(p=>p.pos===pos).length;return `<span class="scarcity-chip ${n<=4?'urgent':''}">${pos} <b>${n}</b></span>`}).join('');const recent=state.history.slice(-8).map(h=>players.find(p=>p.name===h.name)?.pos).filter(Boolean),run=positions.map(pos=>({pos,n:recent.filter(x=>x===pos).length})).sort((a,b)=>b.n-a.n)[0];const current=state.history.length+1,faller=list.slice().sort((a,b)=>(current-b.adp)-(current-a.adp))[0],schedule=list.slice().sort((a,b)=>b.playoff-a.playoff)[0],fit=list.slice().sort((a,b)=>b.fit-a.fit)[0];$('#intelSignals').innerHTML=`<div class="signal"><span>Best faller</span><b>${faller?esc(faller.name):'—'}</b></div><div class="signal"><span>Best schedule</span><b>${schedule?esc(schedule.name):'—'}</b></div><div class="signal"><span>Best roster fit</span><b>${fit?esc(fit.name):'—'}</b></div><div class="signal"><span>Recent position run</span><b>${run&&run.n>=3?run.pos+' · '+run.n+' of last 8':'No major run'}</b></div>`}
function refreshProjectionCopy(){const p=projectedDraftPath(1)[0];if(!p)return;$('#projectedName').textContent=p.name;$('#projectedMeta').textContent=`CBS market projection at pick #${p.target} · Rank #${p.rank} · ADP ${p.estimated?'~':''}${p.adp.toFixed(1)}`;$('#projectedWhy').textContent='This is the player the CBS ranking and ADP order projects to reach your draft slot. It is a market projection, not the BBL recommendation shown above.'}
function openCompare(){const data=state.compare.map(n=>scoredPlayers().find(p=>p.name===n)||players.find(p=>p.name===n)).filter(Boolean);$('#compareGrid').innerHTML=data.map(p=>`<article class="compare-card"><h3>${esc(p.name)}</h3><small>${p.team} · ${p.pos}</small>${[['CBS ADP',(p.estimated?'~':'')+p.adp?.toFixed(1)],['Projected BBL/game',p.bblPpg?.toFixed(1)],['Player value',p.value?.toFixed(1)],['P22–P24 schedule',p.playoff?.toFixed(1)],['Roster fit',p.fit??fitScore(p)],['Next-pick availability',p.availability==null?'—':Math.round(p.availability*100)+'%'],['Overall',p.overall?.toFixed(1)??'—']].map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}<p>${p.why||explanation(p)}</p></article>`).join('');$('#compareModal').classList.add('open');$('#compareModal').setAttribute('aria-hidden','false')}
function render(){renderDraft();renderRoster();renderCoverage();renderHistory();renderSettings();renderIntel();refreshProjectionCopy()}
function newDraft(){const name=prompt('Name this draft:',`Draft ${Object.keys(db.drafts).length+1}`);if(!name)return;const id='draft-'+Date.now();db.drafts[id]=freshDraft(name);db.activeId=id;state=db.drafts[id];save();render();toast('New draft created')}
function switchDraft(id){db.drafts[db.activeId]=state;db.activeId=id;state=db.drafts[id];save();render()}
function backup(){download(`${state.name.replace(/[^a-z0-9]+/gi,'_')}_backup.json`,JSON.stringify({version:2,source:BASE_SEED.settings.source,exported:new Date().toISOString(),db,players},null,2))}
function restore(file){const reader=new FileReader();reader.onload=()=>{try{const x=JSON.parse(reader.result);if(!x.db?.drafts)throw Error();db=x.db;players=x.players||BASE_SEED.players;db.customPlayers=x.players||null;state=db.drafts[db.activeId];save();render();toast('Backup restored')}catch(e){alert('This backup file could not be read.')}};reader.readAsText(file)}
function exportCsv(){const lines=['Pick,Round,Slot,Owner,Player,Team,Position,CBS ADP'];state.history.forEach(h=>{const p=players.find(x=>x.name===h.name)||{};lines.push([h.pick,h.round,h.slot,h.owner,`"${String(h.name).replaceAll('"','""')}"`,p.team||'',p.pos||'',p.adp||''].join(','))});download(`${state.name.replace(/[^a-z0-9]+/gi,'_')}_results.csv`,lines.join('\n'),'text/csv')}
function parseCsv(text){const rows=text.trim().split(/\r?\n/).map(line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out});const head=rows.shift().map(x=>x.toLowerCase().replace(/[^a-z]/g,''));const ix=n=>head.indexOf(n);if(ix('player')<0&&ix('name')<0)throw Error('Missing Player or Name column');return rows.filter(r=>r.length>2).map((r,i)=>{const name=r[ix('player')>=0?ix('player'):ix('name')],old=players.find(p=>p.name.toLowerCase()===name.toLowerCase());return {rank:Number(r[ix('rank')])||i+1,name,pos:r[ix('position')]||r[ix('pos')]||old?.pos||'',team:r[ix('team')]||old?.team||'',adp:Number(r[ix('adp')])||old?.adp||999,value:Number(r[ix('bblvalue')])||old?.value||Math.max(40,100-i*.34),playoff:Number(r[ix('playoffvalue')])||old?.playoff||60}})}
function importCsv(file){const reader=new FileReader();reader.onload=()=>{try{players=parseCsv(reader.result);db.customPlayers=players;save();render();toast(`${players.length} players imported`)}catch(e){alert('CSV import failed: '+e.message)}};reader.readAsText(file)}
function initUi(){
  $('.nav').insertAdjacentHTML('beforeend','<button data-view="history">Draft History</button>');
  $('.topbar .nav').insertAdjacentHTML('beforebegin','<div class="draft-switcher"><select id="draftSelect" class="select"></select><button id="newDraft" class="action">New</button><button id="themeToggle" class="action" title="Switch appearance">◐</button></div>');
  $('.tools').insertAdjacentHTML('beforeend','<select id="teamFilter" class="select"><option value="">All teams</option>'+[...new Set(players.map(p=>p.team))].sort().map(x=>`<option>${x}</option>`).join('')+'</select><select id="callFilter" class="select"><option value="">All calls</option><option>TAKE NOW</option><option>GOOD VALUE</option><option>WAIT</option></select><select id="sortPlayers" class="select sort-select"><option value="rank" selected>Sort: CBS ranking</option><option value="adp">Sort: CBS ADP</option><option value="overall">Sort: Recommendation</option><option value="value">Sort: BBL value</option><option value="playoff">Sort: Playoffs</option><option value="fit">Sort: Fit</option></select>');
  $('.recommend').insertAdjacentHTML('afterend','<section class="panel projected"><div class="panel-head"><div><div class="eyebrow">Projected selection</div><h2 id="projectedName">—</h2><div class="count" id="projectedMeta"></div></div></div><div class="side-list"><div id="projectedWhy" class="why"></div></div></section>');
  $('.projected').insertAdjacentElement('afterend',$('#miniAlerts').closest('.panel'));
  $('.layout>section.panel .table-wrap').insertAdjacentHTML('afterend','<section class="draft-intel"><div class="intel-title"><div><div class="eyebrow">Draft intelligence</div><h2>Next-pick outlook</h2></div><span>Updates after every selection</span></div><div class="intel-grid"><div><h3>Projected selections</h3><div id="intelPicks"></div></div><div><h3>Top-100 players remaining</h3><div id="intelScarcity" class="scarcity-row"></div></div><div class="intel-signals"><h3>Live signals</h3><div id="intelSignals"></div></div></div></section>');
  const firstHeader=$('#playerRows').closest('table').querySelector('thead tr');firstHeader.insertAdjacentHTML('afterbegin','<th>Compare</th>');
  $('#maxActive').disabled=true;$('#maxActive').closest('.field').querySelector('label').textContent='Daily active lineup (fixed)';
  $('#maxActive').closest('.field').insertAdjacentHTML('afterend','<div class="field"><label for="draftPosition">Your draft position</label><select id="draftPosition" class="select">'+Array.from({length:BASE_SEED.settings.teams},(_,i)=>`<option value="${i+1}">Slot ${i+1}</option>`).join('')+'</select></div><div class="settings-note lineup-note"><b>League lineup:</b> 1 G, 1 F, 1 C, 2 G/F/C flex, and 8 bench spots (13 rounds total).</div>');
  $('#settings .settings-note:not(.lineup-note)').insertAdjacentHTML('beforebegin','<div class="settings-actions"><button id="backupSettings" class="btn">Download backup</button><button id="restoreDraft" class="btn">Restore backup</button><button id="importCsv" class="btn">Import player CSV</button><button id="restoreCbs" class="btn">Restore embedded CBS pool</button></div><div class="settings-note source-line">Player pool: '+esc(BASE_SEED.settings.source)+' snapshot dated '+esc(BASE_SEED.settings.sourceDate)+'. The app remains fully offline.</div>');
  $('.source-line').insertAdjacentHTML('beforeend','<br>BBL Player Value uses CBS projected FGM, FGA, FTM, FTA, PTS, REB, AST, STL, BLK, turnovers and 3PM under the league scoring rules. CBS projections do not include personal fouls, so PF is estimated by listed position. Special G/F/C bonuses use the single CBS-listed draft position.');
}
initUi();
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){$$('.nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(x=>x.classList.toggle('active',x.id===b.dataset.view));return}if(b.dataset.mine)mark(b.dataset.mine,'mine');if(b.dataset.taken)mark(b.dataset.taken,'taken');if(b.dataset.removeName){const i=state.history.findIndex(x=>x.name===b.dataset.removeName);if(i>=0)removePick(i)}if(b.dataset.removePick!==undefined)removePick(Number(b.dataset.removePick))});
document.addEventListener('change',e=>{if(e.target.dataset.compare){const n=e.target.dataset.compare;state.compare=e.target.checked?[...new Set([...state.compare,n])]:state.compare.filter(x=>x!==n);if(state.compare.length>3)state.compare=state.compare.slice(-3);save();renderDraft()}});
['search','position','teamFilter','callFilter','sortPlayers'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderDraft));
$('#undo').addEventListener('click',undo);$('#reset').addEventListener('click',resetDraft);$('#newDraft').addEventListener('click',newDraft);$('#draftSelect').addEventListener('change',e=>switchDraft(e.target.value));$('#themeToggle').addEventListener('click',()=>{state.theme=state.theme==='light'?'dark':'light';save();renderSettings()});
$('#draftPosition').addEventListener('change',e=>{state.draftSlot=Math.max(1,Math.min(BASE_SEED.settings.teams,Number(e.target.value)||BASE_SEED.settings.slot));save();render();toast(`Draft position changed to slot ${state.draftSlot}`)});['Value','Playoff','Fit'].forEach((n,i)=>$('#weight'+n).addEventListener('input',e=>{state.weights[i]=Number(e.target.value)/100;save();render()}));
$('#clearCompare').addEventListener('click',()=>{state.compare=[];save();renderDraft()});$('#openCompare').addEventListener('click',openCompare);$('#closeCompare').addEventListener('click',()=>$('#compareModal').classList.remove('open'));$('#compareModal').addEventListener('click',e=>{if(e.target.id==='compareModal')e.currentTarget.classList.remove('open')});
$('#backupDraft').addEventListener('click',backup);$('#backupSettings').addEventListener('click',backup);$('#restoreDraft').addEventListener('click',()=>$('#restoreInput').click());$('#restoreInput').addEventListener('change',e=>e.target.files[0]&&restore(e.target.files[0]));$('#exportCsv').addEventListener('click',exportCsv);$('#importCsv').addEventListener('click',()=>$('#csvInput').click());$('#csvInput').addEventListener('change',e=>e.target.files[0]&&importCsv(e.target.files[0]));$('#restoreCbs').addEventListener('click',()=>{if(confirm('Replace the current custom player pool with the embedded CBS pool?')){players=BASE_SEED.players;db.customPlayers=null;save();location.reload()}});
render();
